def forecast_actual_rows():
    return (
        {
            "ticker": "VCB",
            "timeframe": "1 ngày",
            "prediction_timestamp": "2026-01-01T09:00:00",
            "horizon_steps": 1,
            "forecast_diagnostic": "positive_bias",
            "actual_future_return": 0.02,
            "actual_direction_label": "positive",
            "engine_id": "engine-a",
            "model_family": "classification",
            "diagnostic_score": 0.95,
            "confidence": 0.8,
        },
        {
            "ticker": "VCB",
            "timeframe": "1 ngày",
            "prediction_timestamp": "2026-01-02T09:00:00",
            "horizon_steps": 1,
            "forecast_diagnostic": "positive_bias",
            "actual_future_return": -0.01,
            "actual_direction_label": "negative",
            "engine_id": "engine-b",
            "model_family": "classification",
            "diagnostic_score": 0.90,
            "confidence": 0.7,
        },
        {
            "ticker": "BID",
            "timeframe": "2h",
            "prediction_timestamp": "2026-01-03T09:00:00",
            "horizon_steps": 2,
            "forecast_diagnostic": "negative_bias",
            "actual_future_return": -0.03,
            "actual_direction_label": "negative",
            "engine_id": "engine-c",
            "model_family": "baseline",
            "diagnostic_score": 0.85,
            "confidence": 0.9,
        },
        {
            "ticker": "BID",
            "timeframe": "2h",
            "prediction_timestamp": "2026-01-04T09:00:00",
            "horizon_steps": 2,
            "forecast_diagnostic": "negative_bias",
            "actual_future_return": 0.01,
            "actual_direction_label": "positive",
            "engine_id": "engine-d",
            "model_family": "baseline",
            "diagnostic_score": 0.80,
            "confidence": 0.6,
        },
        {
            "ticker": "CTG",
            "timeframe": "5p",
            "prediction_timestamp": "2026-01-05T09:00:00",
            "horizon_steps": 5,
            "forecast_diagnostic": "neutral_or_uncertain",
            "actual_future_return": 0.00,
            "actual_direction_label": "flat",
            "model_family": "classification",
            "diagnostic_score": 0.70,
            "confidence": 0.5,
        },
        {
            "ticker": "CTG",
            "timeframe": "5p",
            "prediction_timestamp": "2026-01-06T09:00:00",
            "horizon_steps": 5,
            "forecast_diagnostic": "insufficient_evidence",
            "actual_future_return": 0.01,
            "actual_direction_label": "positive",
            "model_family": "statistical",
            "diagnostic_score": 0.60,
            "confidence": 0.4,
        },
        {
            "ticker": "MBB",
            "timeframe": "10p",
            "prediction_timestamp": "2026-01-07T09:00:00",
            "horizon_steps": 10,
            "forecast_diagnostic": "exploratory_only",
            "actual_future_return": -0.02,
            "actual_direction_label": "negative",
            "model_family": "deep_learning",
            "diagnostic_score": 0.50,
            "confidence": 0.3,
        },
    )
